const express = require("express");
const app = express();
const connectDb = require("./config/db.js");
const teacherRoute = require("./routes/teacher.route.js");
const studentRoute = require("./routes/student.route.js");
const adminRoute = require("./routes/adminrout.js");
const dotenv = require("dotenv");
const cors = require("cors");
dotenv.config();
const port = process.env.PORT || 5000;
connectDb();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cors());
app.use("/api/teacher", teacherRoute);
app.use("/api/student", studentRoute);
app.use("/api/admin", adminRoute);
app.listen(port, () => {
  console.log(`Server is runing at http://localhost:${port}`);
});
